name: Build and Deploy React App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_EC2_API_URL: ${{ secrets.VITE_EC2_API_URL }}

    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      repo_name: ${{ steps.define_repo_name.outputs.repo_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Instalar dependências
        run: npm install --force

      - name: Instalar semver
        run: npm install -g semver

      - name: Criar nova tag caso não exista
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$(git tag)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git tag -a v0.0.0 -m "Initial release"
            git push origin v0.0.0
          else
            echo "Tag v0.0.0 já existe — nenhuma ação necessária."
          fi

      - name: Calcular nova versão
        id: version
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$LAST_TAG" ]; then
            LAST_TAG="v0.0.0"
          fi
          echo "Versão Atual: $LAST_TAG"
          
          if [ "$LAST_TAG" = "v0.0.0" ]; then
            COMMITS=$(git log --pretty=format:"%s")
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"%s")
          fi
          
          echo "Commits desde a última tag:"
          echo "$COMMITS"
          
          # Inicializando variáveis
          MAJOR=0
          MINOR=0
          PATCH=0
          
          # Analisando mensagens de commit
          for COMMIT in "$COMMITS"; do
            if [[ "$COMMIT" == *"BREAKING CHANGE"* ]]; then
              MAJOR=1
            elif [[ "$COMMIT" == *"feat"* ]]; then
              MINOR=1
            elif [[ "$COMMIT" == *"fix"* ]]; then
              PATCH=1
            fi
          done
          
          CURRENT_VERSION=${LAST_TAG#v}
          NEW_VERSION=$CURRENT_VERSION
          if [[ $MAJOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i major $CURRENT_VERSION)
          elif [[ $MINOR -eq 1 ]]; then
            NEW_VERSION=$(semver -i minor $CURRENT_VERSION)
          elif [[ $PATCH -eq 1 ]]; then
            NEW_VERSION=$(semver -i patch $CURRENT_VERSION)
          fi
          
          echo "Versões (atual / nova): $CURRENT_VERSION # $NEW_VERSION"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          if [ "$CURRENT_VERSION" == "$NEW_VERSION" ]; then
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "new_version=$CURRENT_VERSION" >> $GITHUB_ENV
            echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Definir o nome do repositório
        id: define_repo_name
        run: |
          REPO_NAME="${{ github.repository }}"
          REPO_NAME="${REPO_NAME#*/}"
          REPO_NAME="${REPO_NAME,,}"   # minúsculo
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV 
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "Repositório: $REPO_NAME"

      - name: Verificar e criar repositório no Docker Hub (se necessário)
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Verificando repositório: $REPO_NAME"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u $DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN \
            "https://hub.docker.com/v2/repositories/$DOCKERHUB_USERNAME/$REPO_NAME/")
          
          if [ "$RESPONSE" -eq 404 ]; then
            echo "Repositório não existe. Criando..."
            curl -s -X POST -u $DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN \
              -H "Content-Type: application/json" \
              -d '{"name": "'$REPO_NAME'", "is_private": true}' \
              "https://hub.docker.com/v2/repositories/$DOCKERHUB_USERNAME/"
            echo "Repositório criado com sucesso!"
          else
            echo "Repositório já existe no Docker Hub."
          fi

      - name: Inserir versão no App.tsx
        if: steps.version.outputs.should_deploy == 'true'
        run: |
          echo "🔧 Inserindo versão no src/App.tsx"
          VERSION=${{ steps.version.outputs.new_version }}
          FILE="src/App.tsx"
          if grep -q '</Routes>' "$FILE"; then
          sed -i '/<\/Routes>/a\
            <div className="text-sm italic text-center mt-4 text-gray-500">Versão: '"$VERSION"'</div>' "$FILE"
          echo "✅ Versão $VERSION inserida no frontend"
          else
            echo "⚠️ Nenhum </Routes> encontrado. Nenhuma modificação feita."
          fi

      - name: Criar imagem docker
        if: steps.version.outputs.should_deploy == 'true'
        run: |
          echo "Iniciando build da imagem Docker"
          docker build --build-arg VITE_EC2_API_URL=${{ env.VITE_EC2_API_URL }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ steps.version.outputs.new_version }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ steps.version.outputs.new_version }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest

      - name: Efetuar push da imagem
        if: steps.version.outputs.should_deploy == 'true'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${{ steps.version.outputs.new_version }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:latest

      - name: Atualizar versão no package.json
        if: steps.version.outputs.should_deploy == 'true'
        run: npm version ${{ steps.version.outputs.new_version }} --no-git-tag-version

      - name: Commit e push
        if: steps.version.outputs.should_deploy == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add package.json
          git commit -m "chore(release): version ${{ steps.version.outputs.new_version }}"
          git tag v${{ steps.version.outputs.new_version }}
          git push origin main --tags

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            REPO_NAME="${{ needs.build.outputs.repo_name }}"
            REPO_NAME="${REPO_NAME,,}"
            VERSION="${{ needs.build.outputs.new_version }}"
            IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:$VERSION"
            echo "🔄 Iniciando deploy da imagem: $IMAGE"

            # Garantir que o Docker esteja disponível
            sudo systemctl start docker || sudo service docker start

            # Verificar container existente
            CONTAINER_ID=$(docker ps -aq --filter "name=^/${REPO_NAME}$")
            if [ -n "$CONTAINER_ID" ]; then
              echo "🛑 Parando e removendo container atual..."
              docker rm -f $REPO_NAME || true
            else
              echo "ℹ️ Nenhum container atual encontrado com nome: $REPO_NAME"
            fi

            echo "🧹 Removendo imagem local antiga, se existir..."
            docker rmi -f "$IMAGE" || echo "ℹ️ Nenhuma imagem antiga encontrada"

            echo "⬇️ Baixando nova imagem..."
            docker pull $IMAGE

            echo "🚀 Subindo novo container..."
            docker run -d -p 3000:80 --name $REPO_NAME $IMAGE
